spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/rvo
spring.datasource.username=root
spring.datasource.password=server.admin

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

server.port=8888

path.projectPath=C:/Users/19255/Desktop/dachuang

path.venvPath=D:/Anaconda3/envs/myenv/python.exe

frontIP=127.0.0.1:8888

# C++模拟器程序路径（请根据实际构建结果调整）
path.cppRvoSimulatorPath=C:/Users/19255/Desktop/dachuang/rvo/cpp-rvo-simulator/build/Release/rvo_simulator.exe